pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building Dotnet Code'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing Dotnet Code'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying Dotnet Code'
            }
        }
    }
}
